2025-09-16 17:03:20	WARN	sdcal::calibrater::setvi(bool,bool)	Already using OLD VisibilityIterator.
2025-09-16 17:03:20	SEVERE	sdcal::Calibrater::selectvis (file /source/casa6/casatools/src/code/synthesis/MeasurementComponents/Calibrater.cc, line 4222)	Caught exception: Spw Expression: No match found for 99, 
2025-09-16 17:03:20	SEVERE	sdcal::::	Exception Reported: Error in data selection specification: Spw Expression: No match found for 99, 
2025-09-16 17:03:20	SEVERE	sdcal::::casa	Traceback (most recent call last):
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	             ^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdcal.py", line 46, in sdcal
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	    cb.selectvis(spw=spw, scan=scan, field=field)
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatools/calibrater.py", line 82, in selectvis
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	    return self._swigobj.selectvis(time, spw, scan, field, intent, observation, baseline, uvrange, chanmode, nchan, start, step, mstart, mstep, msselect)
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatools/__casac__/calibrater.py", line 264, in selectvis
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	    return _calibrater.calibrater_selectvis(self, *args, **kwargs)
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:03:20	SEVERE	sdcal::::casa+	RuntimeError: Error in data selection specification: Spw Expression: No match found for 99, 
2025-09-16 17:03:20	SEVERE	sdcal::::casa	Error in data selection specification: Spw Expression: No match found for 99, 
2025-09-16 17:03:20	SEVERE	sdcal::::casa	Task sdcal raised an exception of class RuntimeError with the following message: Error in data selection specification: Spw Expression: No match found for 99, 
