2025-09-16 17:02:55	WARN	sdcal::calibrater::setvi(bool,bool)	Already using OLD VisibilityIterator.
2025-09-16 17:02:55	SEVERE	sdcal::::casa	Traceback (most recent call last):
2025-09-16 17:02:55	SEVERE	sdcal::::casa+	             ^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:02:55	SEVERE	sdcal::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdcal.py", line 151, in sdcal
2025-09-16 17:02:55	SEVERE	sdcal::::casa+	    raise ValueError('Too many edge points. fraction must be < 0.5.')
2025-09-16 17:02:55	SEVERE	sdcal::::casa+	ValueError: Too many edge points. fraction must be < 0.5.
2025-09-16 17:02:55	SEVERE	sdcal::::casa	Too many edge points. fraction must be < 0.5.
2025-09-16 17:02:55	SEVERE	sdcal::::casa	Task sdcal raised an exception of class ValueError with the following message: Too many edge points. fraction must be < 0.5.
