{"name": "test_imageshape_03", "status": "passed", "description": "03. failure case: invalid dir_shape, an exception raises.", "start": 1758038158027, "stop": 1758038158027, "uuid": "f6a7916d-41f4-4de6-8248-15abcc5ad052", "historyId": "68e525ecd2d043fa2c4dde8b8febc298", "testCaseId": "68e525ecd2d043fa2c4dde8b8febc298", "fullName": "casatasks.test_task_imbaseline.TestImageShape#test_imageshape_03", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_imbaseline"}, {"name": "subSuite", "value": "TestImageShape"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_imbaseline"}], "titlePath": ["casatasks", "test_task_imbaseline.py", "TestImageShape"]}