{"name": "test_CAS_6733", "status": "passed", "description": "Verify listobs runs to completion on data set in CAS-6733. This was an infinite loop bugfix", "start": 1758040034990, "stop": 1758040035527, "uuid": "389b685d-dd16-4554-8e1b-9b5868246a61", "historyId": "a882816daa59ebfe84fa9503cbc3c03f", "testCaseId": "a882816daa59ebfe84fa9503cbc3c03f", "fullName": "casatasks.test_task_listobs.test_listobs#test_CAS_6733", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_listobs"}, {"name": "subSuite", "value": "test_listobs"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_listobs"}], "titlePath": ["casatasks", "test_task_listobs.py", "test_listobs"]}