{"name": "test_param01E", "status": "passed", "description": "sdtimeagerage::01E:: timerange = 00:00:00~01:00:00 ERROR case(3600s INSUFFICIENT).", "attachments": [{"name": "stdout", "source": "5657b3bc-8012-4446-9b54-f9b5105da7a7-attachment.txt", "type": "text/plain"}], "start": 1758043653949, "stop": 1758043654345, "uuid": "9581e67f-224b-4125-8b4c-2f652eb82733", "historyId": "cf515839d9150eaadceb0430f8b9f476", "testCaseId": "cf515839d9150eaadceb0430f8b9f476", "fullName": "casatasks.test_task_sdtimeaverage.test_sdtimeaverage#test_param01E", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_sdtimeaverage"}, {"name": "subSuite", "value": "test_sdtimeaverage"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_sdtimeaverage"}], "titlePath": ["casatasks", "test_task_sdtimeaverage.py", "test_sdtimeaverage"]}