{"name": "test_circular_gaussian", "status": "passed", "description": "Test convolved circular gaussian with noise doesn't throw exception (CAS-5211)", "attachments": [{"name": "stderr", "source": "075b684a-c636-4d1c-9f40-848bd67bd9ed-attachment.txt", "type": "text/plain"}], "start": 1758039075782, "stop": 1758039075920, "uuid": "9cbe40cd-af19-44d8-91d6-08421c742ca5", "historyId": "9a8dedf21ef9fd90355a9a6de5a2c26d", "testCaseId": "9a8dedf21ef9fd90355a9a6de5a2c26d", "fullName": "casatasks.test_task_imfit.imfit_test#test_circular_gaussian", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_imfit"}, {"name": "subSuite", "value": "imfit_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_imfit"}], "titlePath": ["casatasks", "test_task_imfit.py", "imfit_test"]}