{"name": "test_noExistingMode", "status": "passed", "description": " 8. test_noExistingMode: Check that an exception is raised when a non-valid mode is given ", "attachments": [{"name": "stderr", "source": "fe93aec5-7aad-49c5-a72a-df4f44d975aa-attachment.txt", "type": "text/plain"}], "start": 1758039093120, "stop": 1758039093123, "uuid": "3142d0cb-47d7-41ef-ab79-9585b6f66c7f", "historyId": "ba145acd2c4f75841df66a6c184391f7", "testCaseId": "ba145acd2c4f75841df66a6c184391f7", "fullName": "casatasks.test_task_imhistory.imhistory_test#test_noExistingMode", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_imhistory"}, {"name": "subSuite", "value": "imhistory_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_imhistory"}], "titlePath": ["casatasks", "test_task_imhistory.py", "imhistory_test"]}