{"name": "test_sdsmooth_03", "status": "passed", "description": "03. failure case: call sdsmooth with invalid image stack, an exception raises.", "start": 1758038160057, "stop": 1758038160082, "uuid": "f2ab0da6-10c5-4c4f-af36-e4dedaf06264", "historyId": "fc2202ed8af85917f4ce5214d9110705", "testCaseId": "fc2202ed8af85917f4ce5214d9110705", "fullName": "casatasks.test_task_imbaseline.TestSdsmooth#test_sdsmooth_03", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_imbaseline"}, {"name": "subSuite", "value": "TestSdsmooth"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_imbaseline"}], "titlePath": ["casatasks", "test_task_imbaseline.py", "TestSdsmooth"]}