{"name": "test_constructedSetUp", "status": "passed", "description": "Test that the coordsys was set up with the right number of coords and type", "attachments": [{"name": "stderr", "source": "5cde2a94-907b-4cc6-9b96-50d977a86581-attachment.txt", "type": "text/plain"}], "start": 1758034595743, "stop": 1758034595744, "uuid": "990226ac-a7a8-41e6-9b8e-7da85510a458", "historyId": "7eb517d99264f0ace34a07f4df2e5f24", "testCaseId": "7eb517d99264f0ace34a07f4df2e5f24", "fullName": "casatools.test_tool_coordsys.coordsys_test#test_constructedSetUp", "labels": [{"name": "parentSuite", "value": "casatools"}, {"name": "suite", "value": "test_tool_coordsys"}, {"name": "subSuite", "value": "coordsys_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "593221-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatools.test_tool_coordsys"}], "titlePath": ["casatools", "test_tool_coordsys.py", "coordsys_test"]}