{"name": "test010", "status": "passed", "description": "Test010: Bad phasecenter reference (CHANGED: raise an error).", "attachments": [{"name": "stderr", "source": "c550931c-fbcb-4362-a0fa-18c043e5e19d-attachment.txt", "type": "text/plain"}], "start": 1758048202116, "stop": 1758048202241, "uuid": "f3f31c6e-44a4-49ef-b395-df81c9be16e3", "historyId": "ac7dad738259ca7ba6a3affb83c0c37b", "testCaseId": "ac7dad738259ca7ba6a3affb83c0c37b", "fullName": "casatasks.test_task_tsdimaging.sdimaging_test0#test010", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_tsdimaging"}, {"name": "subSuite", "value": "sdimaging_test0"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_tsdimaging"}], "titlePath": ["casatasks", "test_task_tsdimaging.py", "sdimaging_test0"]}