{"name": "test_conform3", "status": "passed", "description": "test_conform3: CORRECTED_DATA column exists only for the first MS", "attachments": [{"name": "stderr", "source": "2067be96-919d-4d2e-97d5-f23846cbefd0-attachment.txt", "type": "text/plain"}], "start": 1758042531697, "stop": 1758042532412, "uuid": "7ec59828-d930-427c-9574-c2963c1acb61", "historyId": "5180d8553a04b73f308a7e8c11d2c06c", "testCaseId": "5180d8553a04b73f308a7e8c11d2c06c", "fullName": "casatasks.test_task_sdimaging.sdimaging_ms_conformance#test_conform3", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_sdimaging"}, {"name": "subSuite", "value": "sdimaging_ms_conformance"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_sdimaging"}], "titlePath": ["casatasks", "test_task_sdimaging.py", "sdimaging_ms_conformance"]}